name: camera_lap_timer
description: "Camera-based time measurement application"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+7
  image: ^4.1.3
  flutter_tts: ^3.8.5
  fl_chart: ^0.66.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  google_mobile_ads: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
     - assets/icon.png